# Generated by Django 5.2.17 on 2026-09-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='role',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
