# Generated by Django 5.2.17 on 2026-09-12 14:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
                ('icon_class', models.CharField(max_length=50)),
                ('skill_type', models.CharField(choices=[('technical', 'Technical Skills'), ('soft', 'Soft Skills')], max_length=15)),
            ],
        ),
    ]
