# Generated by Django 5.2.17 on 2026-09-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('hard', 'Hard Skills'), ('soft', 'Soft Skills')], max_length=15),
        ),
    ]
